table fact_sales_target
	lineageTag: 1d35f5f0-705b-4eac-b9c8-33de6ff0e7f5

	column date
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 58b34c6c-9caf-44b6-9392-81b58ccaecbe
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column target_revenue
		dataType: int64
		formatString: 0
		lineageTag: d33f1e72-c6b6-4aa7-bac2-195c0c58b17e
		summarizeBy: sum
		sourceColumn: target_revenue

		annotation SummarizationSetBy = Automatic

	partition fact_sales_target = m
		mode: import
		queryGroup: 03_Facts
		source =
				let
				    Source = sales_targets,
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"Period", "date"}, {"TargetRevenue", "target_revenue"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

