table fact_order_process
	lineageTag: 9ec51ab9-b1a3-4391-b577-8d9e80f8d9e9

	column order_id
		dataType: string
		lineageTag: d4af6d3c-6fbc-4916-a2e8-18346b1d6358
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: int64
		formatString: 0
		lineageTag: 9ddedd5f-3e8d-4d54-86f4-092f10128ffb
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column order_date
		dataType: dateTime
		formatString: yyyy-mm-dd hh:nn:ss
		lineageTag: 145111ff-ccca-4486-9004-f44a34e05b58
		summarizeBy: none
		sourceColumn: order_date

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column ship_date
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: ab89f545-e343-4372-9390-88637a47505d
		summarizeBy: none
		sourceColumn: ship_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column delivery_date
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: f4a41b7e-41be-4054-aace-9a262bfdc784
		summarizeBy: none
		sourceColumn: delivery_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column invoice_date
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 8bae3df9-e588-400c-98b7-1de36b5f8ea2
		summarizeBy: none
		sourceColumn: invoice_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column pay_date
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: b2df612e-5595-466f-b85b-f293de24fbf5
		summarizeBy: none
		sourceColumn: pay_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column order_to_pay = DATEDIFF(fact_order_process[order_date], fact_order_process[pay_date], DAY)
		formatString: 0
		lineageTag: 5e05dd4e-fbea-4b16-b790-319638e36055
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition fact_order_process = m
		mode: import
		queryGroup: 03_Facts
		source =
				let
				    Source = orders,
				    #"Removed Columns" = Table.RemoveColumns(Source,{"CustomerCity", "RegionName", "ShipToCity", "BillToCity", "OrderChannel", "Status", "Priority", "OrderTotal"}),
				    #"Merged Queries" = Table.NestedJoin(#"Removed Columns", {"CustomerName"}, dim_customer, {"customer_name"}, "dim_customer", JoinKind.LeftOuter),
				    #"Expanded dim_customer" = Table.ExpandTableColumn(#"Merged Queries", "dim_customer", {"customer_id"}, {"dim_customer.customer_id"}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Expanded dim_customer",{"OrderID", "dim_customer.customer_id", "CustomerName", "OrderDate"}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Reordered Columns",{"CustomerName"}),
				    #"Merged Queries1" = Table.NestedJoin(#"Removed Columns1", {"OrderID"}, shipments, {"OrderID"}, "shipments", JoinKind.LeftOuter),
				    #"Expanded shipments" = Table.ExpandTableColumn(#"Merged Queries1", "shipments", {"ShipDate", "DeliveryDate"}, {"shipments.ShipDate", "shipments.DeliveryDate"}),
				    #"Merged Queries2" = Table.NestedJoin(#"Expanded shipments", {"OrderID"}, INVOICES, {"OrderID"}, "INVOICES", JoinKind.LeftOuter),
				    #"Expanded INVOICES1" = Table.ExpandTableColumn(#"Merged Queries2", "INVOICES", {"InvoiceID", "InvoiceDate"}, {"INVOICES.InvoiceID", "INVOICES.InvoiceDate"}),
				    #"Merged Queries3" = Table.NestedJoin(#"Expanded INVOICES1", {"INVOICES.InvoiceID"}, payments, {"InvoiceID"}, "payments", JoinKind.LeftOuter),
				    #"Expanded payments" = Table.ExpandTableColumn(#"Merged Queries3", "payments", {"PayDate"}, {"payments.PayDate"}),
				    #"Removed Columns2" = Table.RemoveColumns(#"Expanded payments",{"INVOICES.InvoiceID"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns2",{{"OrderID", "order_id"}, {"dim_customer.customer_id", "customer_id"}, {"OrderDate", "order_date"}, {"shipments.ShipDate", "ship_date"}, {"shipments.DeliveryDate", "delivery_date"}, {"INVOICES.InvoiceDate", "invoice_date"}, {"payments.PayDate", "pay_date"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

